Update patch set 4
Patch Set 4:

Ruchi, do you know why this simple change caused Treehugger test failure?
The following undef error does not seem to be related to warning flags.

packages/apps/Nfc/nci/jni/NativeNfcTag.cpp:1856:5: error: use of undeclared identifier 'ALOGD'

Patch-set: 4
Reviewer: Gerrit User 1052399 <1052399@85c56323-6fa9-3386-8a01-6480fb634889>
Label: Presubmit-Ready=0